#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=00:30:00,vmem=8gb

dwi=$(jq -r .dwi config.json)
bvals=$(jq -r .bvals config.json)
bvecs=$(jq -r .bvecs config.json)

mkdir -p output

echo "Computing colored FA..."
singularity exec -e docker://brainlife/dipy:1.4.1 python compute_cfa.py -dwi $dwi -bvals $bvals -bvecs $bvecs

echo "Masking colored FA..."
singularity exec -e docker://brainlife/fsl:6.0.1 mask.sh $dwi cfa.nii.gz

cp cfa_masked.nii.gz output/peaks.nii.gz

if [ -f 'output/peaks.nii.gz' ]; then 
    echo "Colored FA computed."
else 
    echo "Colored FA missing."
    exit 1
fi
